### ISSUE TITLE
Question: How to use with rest API 

### ISSUE THREAD

**Issue by kashiMathura** [vitalets/playwright-bdd-example#11]
Is there any example for reference on how to use this for api testing framework. Thank you.

**Comment by vitalets** [comment]
I've created example of API testing here: https://github.com/vitalets/playwright-bdd-example/tree/api-testing

The most tricky part - if you want to perform request in one step and check response in the another step.
For example:
```feature
Feature: Test httpbin.org API

    Scenario: /headers
        When I send request to "/headers"
        Then I see in response field "Accept-Encoding" containing "gzip,deflate,br"
```
In that case we need to pass response between steps. In Playwright it's better to do this with fixtures:
```ts
import { APIResponse } from '@playwright/test';
import { test as base } from 'playwright-bdd';

export const test = base.extend<{ lastResponse: { data: APIResponse | null } }>({
  lastResponse: async ({}, use) => use({ data: null }),
});
```
And then step definitions:
```ts
import { expect } from '@playwright/test';
import { createBdd } from 'playwright-bdd';
import { test } from './fixtures';

const { When, Then } = createBdd(test);

When('I send request to {string}', async ({ request, lastResponse }, route: string) => {
  lastResponse.data = await request.get(route);
});

Then('I see in response field {string} containing {string}', async ({ lastResponse }, field: string, value: string) => {
  expect(await lastResponse.data?.json()).toEqual({
    headers: expect.objectContaining({
      [field]: value
    })
  });
});
```

**Comment by kashiMathura** [comment]
I tried to use "And" but it's unable to recognize. Is there any way to Implement "And" along with Given when then?. Thanks

**Comment by kashiMathura** [comment]
How do we configure Run/Debug configuration in intellij?  I wish to execute  and debug by rightclick >  XXX.feature

**Comment by vitalets** [comment]
> I tried to use "And" but it's unable to recognize. Is there any way to Implement "And" along with Given when then?. Thanks

In the step definitions you can implement steps using only `Given, When, Then` functions. In feature files you can use `And / But` instead of any of these keywords. 

> How do we configure Run/Debug configuration in intellij? I wish to execute and debug by rightclick > XXX.feature

Could you try [this](https://vitalets.github.io/playwright-bdd/#/ide-integration?id=intellij-ide-aqua)? If it does not work please provide more details / screenshots, as I don't have Intelliji and it's difficult to reproduce such issues.

**Comment by kashiMathura** [comment]
> > I tried to use "And" but it's unable to recognize. Is there any way to Implement "And" along with Given when then?. Thanks
> 
> In the step definitions you can implement steps using only `Given, When, Then` functions. In feature files you can use `And / But` instead of any of these keywords.
> 
> > How do we configure Run/Debug configuration in intellij? I wish to execute and debug by rightclick > XXX.feature
> 
> Could you try [this](https://vitalets.github.io/playwright-bdd/#/ide-integration?id=intellij-ide-aqua)? If it does not work please provide more details / screenshots, as I don't have Intelliji and it's difficult to reproduce such issues.

I tried to use VS code and cucumber extentions but it's not identifying the steps . for example when I do right ctrl + click its not taking me to step definition and in test explorer I do not find tests . By only npm run test I can execute 
![Uploading image.png…]()

**Comment by vitalets** [comment]
Do you use [this VS Code extension](https://marketplace.visualstudio.com/items?itemName=alexkrechik.cucumberautocomplete)? 
Pls wait for screenshot to upload.

**Comment by kashiMathura** [comment]
Another query, how to execute these tests in parallel, In playwright config we have "export default defineConfig({
  // Each test is given 30 seconds.
  timeout: 100000,
  /* Retries */
  retries: 2,
  /* Opt out of parallel tests */
  workers: 7,
  fullyParallel: true,

**Comment by vitalets** [comment]
> Another query, how to execute these tests in parallel

All Playwright config options work with playwright-bdd. For example:
```ts
import { defineConfig } from '@playwright/test';
import { defineBddConfig } from 'playwright-bdd';

const testDir = defineBddConfig({
  paths: ['sample.feature'],
  require: ['steps.js'],
});

export default defineConfig({
  testDir,
  // Each test is given 30 seconds.
  timeout: 100000,
  /* Retries */
  retries: 2,
  /* Opt out of parallel tests */
  workers: 7,
  fullyParallel: true,
});
```

**Comment by kashiMathura** [comment]
> ```ts
>  /* Retries */
>   retries: 2,
>   /* Opt out of parallel tests */
>   workers: 7,
>   fullyParallel: true,
> ```

oh sorry. My bad. I tried to define in defineBddConfig instead of defineConfig
