### ISSUE TITLE
Error by run test from Test Explorer

### ISSUE THREAD

**Issue by PavelGlebovAndritz** [vitalets/playwright-bdd-example#13]
Just clone the project.
**npm test** works without error and shows 1 passed test. 
But when I run test from Playwright test explorer I got the error.. 
![image](https://github.com/vitalets/playwright-bdd-example/assets/135133941/26c9ab2e-3666-4805-b6d7-254e7d128b18)

**Comment by vitalets** [comment]
Wrapping into https://github.com/vitalets/playwright-bdd/issues/94
Could you provide in the main issue full error output showing First and Second paths of requiring Playwright?
