### ISSUE TITLE
Question - Is it possible to use createBdd func without an argument?

### ISSUE THREAD

**Issue by 1RossFisher1** [vitalets/playwright-bdd-example#15]
It appears in the docs that you can use this function with no arguements. When I try to use it, it appears to be written to require you to have fixtures and there cannot be no arguement like is shown in the docs. 

![image](https://github.com/vitalets/playwright-bdd-example/assets/109974928/dde5b58e-6a0c-4c85-a778-17ac6cfdf496)

![image](https://github.com/vitalets/playwright-bdd-example/assets/109974928/cb673c07-5deb-49b4-8f01-901b010c4a29)
. 
![image](https://github.com/vitalets/playwright-bdd-example/assets/109974928/98426fe1-b69d-4db7-afdd-c1152798e01a)

**Comment by vitalets** [comment]
Yes, you can use createBdd without an argument if you don't use custom fixtures in steps.
Your code is correct, the only thing - `User logs in` step is using `page`, so you need to pass `page` as argument:
```js
Given('User logs in', async function ({ page }) {
  await page.goto(...)
});

**Comment by 1RossFisher1** [comment]
Hey @vitalets thanks for the speedy reply. I didnt realise I had missed that. Unfortunately this has still not solved my issue and I am getting the same error message. 

```
import { config } from "../config";
import { createBdd } from 'playwright-bdd';
import { expect, page } from '@playwright/test';

const { Given, When, Then } = createBdd();


Given('User logs in', async function ({ page }) {
    await page.goto(config.baseUrl);
    await page.locator('text=Windows').click();
    await page.waitForLoadState("networkidle");
});
```

**Comment by vitalets** [comment]
@1RossFisher1 could you please reproduce this error on playwright-bdd-example by this [instruction](https://github.com/vitalets/playwright-bdd-example/blob/main/README.md)?
