### ISSUE TITLE
Error on Fixture

### ISSUE THREAD

**Issue by vcardins** [vitalets/playwright-bdd-example#2]
Hi,

I'm getting the following error:
![image](https://github.com/vitalets/playwright-bdd-example/assets/2383329/288bd07f-f30d-4a31-a078-edf371533428)

Any idea?

**Comment by vitalets** [comment]
Hi! 
Could you check your Typescript version? 
It should be v5+ to support actual decorators syntax instead of legacy one.

**Comment by vcardins** [comment]
Hi, yes, I do have the latest typescript version 5.2.2.
![image](https://github.com/vitalets/playwright-bdd-example/assets/2383329/720431ef-a33d-46f7-9714-b01d5ada6da1)

Any suggestion?

**Comment by vcardins** [comment]
Maybe it has to do with https://github.com/microsoft/TypeScript/issues/53208. What's your TS version?

**Comment by vitalets** [comment]
My TS version is also 5.2.2.

Lets try the following:
1. run in terminal `npx tsc --version && npx tsc --noEmit` to check installed ts version (compared to vscode built-in)
2. could you click on `createDecorators.d.ts` in error message to see what type actually used for checking?

**Comment by vitalets** [comment]
Btw, I've added `typescript` to devDependencies of playwright-bdd-example, as it was missing (but it's important!) 👍

**Comment by vcardins** [comment]
Hey! Not sure this is exactly what you're looking for ...

![image](https://github.com/vitalets/playwright-bdd-example/assets/2383329/4d95d385-bc9c-4d29-8fc8-b818e87bbcb5)

![image](https://github.com/vitalets/playwright-bdd-example/assets/2383329/cdca3b70-dc83-49ab-82f7-51121a3333f5)

**Comment by vcardins** [comment]
Okay. The error happens when I tried to integrate the example into my code base, when I closed this repo it ran fine. I'm going to investigate and keep you posted.
