### ISSUE TITLE
How to mention multiple fixture in playwright.config.ts file 

### ISSUE THREAD

**Issue by kalyankumar381** [vitalets/playwright-bdd-example#5]
Created two fixture and want to use it but unable to mention config file 
const testDir = defineBddConfig({
	importTestFrom: 'tests/pwbdd-examples/steps/fixtures.ts',
	paths: ['tests/pwbdd-examples/features/**/*.feature'],
	require: ['tests/pwbdd-examples/steps/**/*.ts'],
	tags: '@test2'
});

importTestFrom - is there only fixture can import
how about two fixture want to use

**Comment by vitalets** [comment]
Lets track it in `playwright-bdd` repo: https://github.com/vitalets/playwright-bdd/issues/66
